### ISSUE TITLE
缺少模块

### ISSUE THREAD

**Issue by BaiLonghai** [imyuanx/xmly-download#1]
![image](https://user-images.githubusercontent.com/47236864/215105300-937f547c-07f8-4795-8b35-cbf365d5b101.png)

**Comment by imyuanx** [comment]
由于防止敏感信息泄漏，所以在本地运行需要复制`config.js`文件并且重命名为`config-local.js`，在`config-local.js`文件内填写相关配置（此文件不会被提交）。
更新了相关文档：https://github.com/yunying1/xmly-download#%E9%85%8D%E7%BD%AE

如果还有其他问题，随时可以打开这个 issue
